Update to fix issues

diff --git a/.github/workflows/activation.yml b/.github/workflows/activation.yml
--- a/.github/workflows/activation.yml
+++ b/.github/workflows/activation.yml
@@ -17,18 +17,20 @@ jobs:
           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
         with:
-          projectPath: ./
-          githubToken: ${{ secrets.GITHUB_TOKEN }}
+          #projectPath: ./
+          #githubToken: ${{ secrets.GITHUB_TOKEN }}
+          unityVersion: 2022.3.33f1
 
       - name: Debug - Search for activation file
         run: |
-          echo "Searching for activation file (ManualActivationFile.lic):"
+          echo "Current directory:"
+          pwd
+          echo "Searching for .lic files:"
           find . -name "*.lic" -type f
           echo "Contents of _activate-license directory:"
-          ls -la ./_activate-license
-          echo "Contents of docs/_static directory:"
-          ls -la ./docs/_static
-
+          ls -la ./_activate-license || echo "_activate-license directory not found"
+          echo "Contents of current directory:"
+          ls -la
 
       - uses: actions/upload-artifact@v4
         if: success()
@@ -37,5 +39,4 @@ jobs:
           path: |
             ./_activate-license/*.lic
             ./docs/_static/*.lic
-          if-no-files-found: warn
-          #if-no-files-found: error
+          if-no-files-found: error
