Feat/run id docker image (#120)
* Fix Docker Image generation

* Updated according to wait-for-check documentation

* Comment out code

* Clean up code

* Add missing code

* Correct missed placed ID tag

* Remove if-condition

* Simplify

diff --git a/.github/workflows/publish-docker-image.yml b/.github/workflows/publish-docker-image.yml
--- a/.github/workflows/publish-docker-image.yml
+++ b/.github/workflows/publish-docker-image.yml
@@ -21,31 +21,9 @@ env:
   DOCKER_NAMESPACE: chrisjcc
   DOCKER_REPOSITORY: replicantdrivesim
 
+
 jobs:
-  wait-for-unity-build:
-    runs-on: ubuntu-latest
-    #if: ${{ github.event_name == 'workflow_run' }}  # Only run this job for workflow_run events
-    steps:
-      - name: Wait for Unity Build Artifact
-        uses: fountainhead/action-wait-for-check@v1.2.0
-        id: wait-for-build
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: Publish PyPI Package
-          #ref: ${{ github.event.client_payload.ref || github.ref }}
-          ref: ${{ github.sha }}  # Use the commit SHA instead
-          timeoutSeconds: 3600
-
-      - name: Do something with a passing build
-        if: steps.wait-for-build.outputs.conclusion == 'success'
-        run: echo "Build succeeded"
-
-      - name: Do something with a failing build
-        if: steps.wait-for-build.outputs.conclusion == 'failure'
-        run: echo "Build failed"
-
   build-and-push-docker-image:
-    needs: [wait-for-unity-build]
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
     permissions:
@@ -55,6 +33,21 @@ jobs:
     outputs:
       VERSION: ${{ steps.get_version.outputs.VERSION }}
     steps:
+      - name: Wait for Unity Build Artifact
+        uses: fountainhead/action-wait-for-check@v1.2.0
+        id: wait-for-build
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          checkName: Publish PyPI Package
+          ref: ${{ github.sha || github.event.client_payload.ref || github.ref }}
+          timeoutSeconds: 3600
+
+      - name: Check build status
+        if: steps.wait-for-build.outputs.conclusion != 'success'
+        run: |
+          echo "Build failed or timed out"
+          exit 1
+
       - name: Checkout Git repository
         uses: actions/checkout@v4
         with:
